nama = input   ("Nama                 : ")
nim = input    ("NIM                  : ")
paralel = input("Kelas Paralel        : ")
tempat, hari, bulan, tahun = input ("Tempat/Tanggal Lahir : {} / {} - {} -{}").format().split()
alamat = input ("Alamat               : ")
hobi = input   ("Hobby                : ")
hp = input     ("No. Hp               : ")
print ("\n")

print("Nama                 : ", nama)
print("NIM                  : ", nim)
print("Kelas Paralel        : ", paralel)
print("Tempat/Tanggal Lahir : {} / {} - {} - {}".format(tempat,hari,bulan,tahun))
print("Alamat               : ", alamat)
print("Hobby                : ", hobi)
print("No. Hp               : ", hp)